### ISSUE TITLE
Implement 3box identity resolution in aragon client

### ISSUE THREAD

**Issue by Schwartz10** [AutarkLabs/aragon-profile#17]
implement https://github.com/AutarkLabs/aragon-profile/issues/16

**Comment by Schwartz10** [comment]
Here's the spec: https://github.com/aragon/aragon/issues/854, follow issue there

**Comment by Schwartz10** [comment]
Putting this ticket on hold for now, we need a better understanding of what this will take from the aragon side of things.

**Comment by stellarmagnet** [comment]
Closing this
