### ISSUE TITLE
Ensure the user's profile is either correctly loaded or not shown

### ISSUE THREAD

**Issue by rkzel** [AutarkLabs/aragon-profile#29]
When browser is reopened (after crash or being killed) user can see profile page without data. I'm not sure what is expected, but it probably should be something different?

Steps to reproduce:
1. Be logged in to profiles,
2. Kill the browser and re-open, do not log in to MetaMask,
3. Go to the DAO and open Profile.

What should be displayed is Profile app without data, and clicking on any link ("add work" for example) will result in blank page and lots of errors like the one below:

Uncaught TypeError: Cannot read property 'image' of undefined
    at ProfilePicture (ProfilePicture.js:60)

Also, "Log in" button is disabled.

**Comment by Schwartz10** [comment]
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/12353734/57482937-e75dcb00-7273-11e9-91df-e9fb3a61ed67.png">

Yalda what should the profile look like if MM is locked?
