### ISSUE TITLE
Month and year dropdowns are really long and add a scroll to the modal

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/aragon-profile#33]
Implement a min/max height and overflow

![image](https://user-images.githubusercontent.com/2584493/60274981-63ca6d00-98f9-11e9-9eb5-319aa89a8b00.png)

**Comment by rkzel** [comment]
This issue has a bounty attached to it.
Amount: 3.00 autark
Deadline: Wed, 31 Jul 2019 21:26:39 GMT
