### ISSUE TITLE
Increase the breakpoint for when the page turns into single column

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/aragon-profile#38]
It should convert into single column much before this breakpoint

What breakpoints we using now?

![image](https://user-images.githubusercontent.com/2584493/60277844-a3e01e80-98fe-11e9-9601-c288e0e94f97.png)

**Comment by rkzel** [comment]
This issue has a bounty attached to it.
Amount: 3.00 autark
Deadline: Sat, 13 Jul 2019 04:09:55 GMT

**Comment by rkzel** [comment]
640px is the threshold, but there is switch from two to one column happens at about 710px, as my browser reports. What should be the minimum width of a column?
