### ISSUE TITLE
App wide error handling

### ISSUE THREAD

**Issue by Schwartz10** [AutarkLabs/aragon-profile#43]
@rkzel I'm concerned that the application errors take different shapes and forms. This ticket is to do a little `chaos-monkey` testing on profiles. Insert random errors in different parts of the app (just `throw new Error()` throughout different operations) and see how the app responds. We should make clear what an error is in the app and how we handle it. Are errors strings or objects?

**Comment by rkzel** [comment]
Please see ticket #49 (isn't it kind of the same?): exceptions are objects, simple validation errors are strings.
