### ISSUE TITLE
Handle when i'm viewing my profile but i'm not signed in to metamask

### ISSUE THREAD

**Issue by Schwartz10** [AutarkLabs/aragon-profile#52]
(should show no profile state) https://projects.invisionapp.com/d/?origin=v7#/console/17511474/363316804/preview

**Comment by rkzel** [comment]
When I'm not signed to MM then whatever public profile I view should be viewed in RO mode - including my own, right?

**Comment by rkzel** [comment]
This issue has a bounty attached to it.
Amount: 1.00 autark
Deadline: Wed, 31 Jul 2019 21:26:39 GMT
