### ISSUE TITLE
http://localhost:3000/#/jonnnnnny/profile/ breaks view mode calculation

### ISSUE THREAD

**Issue by Schwartz10** [AutarkLabs/aragon-profile#63]
`http://localhost:3000/#/jonnnnnny/profile/` --> the `viewMode` calculation breaks here because it sees the `/` and then tries to read the eth address after that.

http://localhost:3000/#/jonnnnnny/profile/ should be the same as http://localhost:3000/#/jonnnnnny/profile

**Comment by rkzel** [comment]
This issue has a bounty attached to it.
Amount: 5.00 autark
Deadline: Wed, 31 Jul 2019 21:26:39 GMT
