### ISSUE TITLE
Document the changes required to allow any organization to be added to a user's profile

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/aragon-profile#69]
Currently there are technical limitations with regards to adding an organization to a user profile where the user can only add their current DAO as an "organization".

I'd like a document created in Notion that describes the following:
1) The current limitations
2) The enhancements required to support any organization being added
3) Whether the enhancements can be incorporated in our "Organization Settings" work (see the spec here: https://www.notion.so/autark/Organization-Settings-296282154d6848f0966c39c3b0762b9e)

**Comment by stellarmagnet** [comment]
This is a blocker for design work and needs to be prioritized.

**Comment by rkzel** [comment]
This issue has a bounty attached to it.
Amount: 2.00 autark
Deadline: Wed, 07 Aug 2019 12:46:58 GMT

**Comment by Quazia** [comment]
https://www.notion.so/autark/Arbitrary-Membership-Checking-4fb83d9c80764a049cf2390710e550c3

**Comment by stellarmagnet** [comment]
Completed
